version: '3.9'
services:
  db:
    build: ./db
    ports:
      - 5432:5432
  api:
    build: ./api
    depends_on:
      - db
    ports:
      - 8080:8080
  web:
    build: ./web
    ports:
      - 8181:8080
    environment:
      - REACT_APP_API=http://localhost:8080
